baseURL = 'https://pantarhei.github.io/site-web/public/'
title = 'Segfault45'
theme = 'risotto'
author = 'Segfault45'
copyright = 'Â© [void void](https://joeroe.io) & [void](https://github.com/joeroe/risotto/graphs/contributors).'

languageCode = 'en'
DefaultContentLanguage = 'en'
enableInlineShortcodes = true

contentDir = "content"


ignoreErrors = ["error-remote-getjson"]

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

pluralizeListTitles = false


[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "Segfault45"
description = "Une voiture aux roues carrÃ©es pourra rouler sur une route au revÃªtement composÃ© de tronÃ§ons de cosinus hyperboliques (une citation volÃ©e). "
# unicode/emoji logo:
#logo = "ðŸš"
# or use an image:
#logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/PantaRhei"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:segfault45@segfault45.com"

#[[params.socialLinks]]
#icon = "ai ai-orcid"
#title = "ORCID"
#url = "https://orcid.org/0000-0001-2345-6789"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "radio"
name = "Radio"
url = "/radio/"
weight = 10

[[menu.main]]
identifier = "links"
name = "Links"
url = "/links/"
weight = 10


[[menu.main]]
identifier = "cheat_sheet"
name = "Cheat sheet"
url = "/cheat_sheet/"
weight = 10

#[taxonomies]
#category = "categories"
#tag = "tags"
#series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

# Table of contents
# Add toc = true to content front matter to enable
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

[privacy]

[privacy.vimeo]
disabled = false
#simple = true

[privacy.twitter]
disabled = false


[privacy.instagram]
disabled = false
#simple = true

[privacy.youtube]
disabled = false
#privacyEnhanced = true
